version: '3.7'
services:
    db:
        image: postgres:12
        env_file:
            - '.env'
        ports:
            - '2345:5432'
        volumes:
            - ./data:/var/lib/postgresql
